# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotbarslocal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotbarslocal.Review')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotbarslocal.Bar')),
            ],
            bases=('hotbarslocal.review',),
        ),
    ]
