# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotbarslocal', '0002_barreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='phone',
        ),
    ]
